name: mcp_dart
description: Dart Implementation of Model Context Protocol (MCP) SDK.
version: 0.4.3
repository: https://github.com/leehack/mcp_dart

environment:
  sdk: ^3.0.0

# dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
