name: mcp_dart
description: Dart Impementation of Model Context Protocol (MCP) SDK.
version: 0.1.0
repository: https://github.com/leehack/mcp_dart

environment:
  sdk: ^3.7.2

dependencies:
  uuid: ^4.5.1
  shelf: ^1.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
